Upgrade to ACA-Py 0.6.0, configuration tweaks
bcgov/indy-email-verification pull request #66
Opened 2021-02-26 20:54 UTC by esune

There are some change sin the Jenkinsfile, but they are not actually being used right now.

2021-02-26 21:25 UTC, WadeBarnes approved these changes

2021-02-26 21:25 UTC, WadeBarnes requested changes
DCO Sign-off needs to be fixed.

2021-02-26 22:22 UTC, wadeking98 approved these changes
looks good to me aside from dco check

2021-02-27 13:26 UTC, WadeBarnes approved these changes

2021-02-27 13:27 UTC, merged